# -*- coding: utf-8 -*-
"""Hacking the dating.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3s7eovL7xqb4EbjQI4pA0ypvTqQRqcw

# Get Our Data again to test Data Imputation
"""

!gdown 1qr3nBZPdy4XHLiVQ7cfFYs07CCRY8flM

# Commented out IPython magic to ensure Python compatibility.
# Import data analysis modules
import numpy as np
import pandas as pd
# Import visualization modules
import matplotlib.pyplot as plt
import seaborn as sns
import chardet
# %matplotlib inline
with open('Speed Dating Data.csv', 'rb') as f:
    encoding = chardet.detect(f.read())['encoding']
# Use pandas to read csv file
dating_df = pd.read_csv('Speed Dating Data.csv', encoding=encoding)
dating_df

dating_df.nunique()

"""# Descriptive statistics"""

statistics = dating_df.describe()
statistics

"""# Visualize"""

missing_values = dating_df.isnull().sum()
missing_values

plt.figure(figsize=(240,96))
sns.heatmap(dating_df.corr(), vmax=0.6, square=True, annot=True)